### ISSUE TITLE
[Request] Some way to identify grave owner

### ISSUE THREAD

**Issue by theboo** [Quarris/EnigmaticGraves#11]
Currently there is no way to identify who a grave out in the world might belong to.

Suggest to either make the name of the grave the player's name so it is visible in mods like The One Probe/other WAILA type mods, or write the player's name on the grave itself.

**Comment by Fireztonez** [comment]
I agreed, having the name write directly on the grave, little like the grave of Corail Tombstone would be really nice!

**Comment by Quarris** [comment]
![image](https://user-images.githubusercontent.com/6171764/127028947-e53f4450-a814-4700-8708-7e736b90b6da.png)
I got this for yall. Not sure yet if we're going to add a name onto the grave itself yet.
