### ISSUE TITLE
Curse of Binding not being Deleted 

### ISSUE THREAD

**Issue by Ridanisaurus** [Quarris/EnigmaticGraves#17]
If the player is wearing an armor piece with Curse of Binding, and they die, the item is saved, and they end up re-wearing it upon the Grave retrieval. 
I think the item should be deleted upon death, and not stored in the Grave.

**Comment by Quarris** [comment]
I feel like it shouldn't be deleted but instead just placed in the main inventory. Curse of Binding items don't get deleted on death by default.
