### ISSUE TITLE
A way to remove a grave

### ISSUE THREAD

**Issue by F0gboy** [Quarris/EnigmaticGraves#18]
Need a way to remove others gravestone, as an admin/OP ofcourse.

**Comment by Quarris** [comment]
Thats a good point. How do you think that should be done? How about RClicking with an empty grave finder (accessible only through creative menu) on the grave by an admin?

**Comment by F0gboy** [comment]
Yeah that would be great! im sure there is a way to do it now, since its an entity with something like this: /kill @e[type=something something] but thats just not a viable solutiont tbh.

but yeah the empty grave finder idea is good
