### ISSUE TITLE
Crashes client after FML mod loading without any error message

### ISSUE THREAD

**Issue by SamhitApple** [Quarris/EnigmaticGraves#19]
The client crashes after a couple of seconds of Forge loading mods with this mod installed along with others without any error pop-up during start up.
 -Here's the crash report: https://pastebin.com/VkGYSavp

**Comment by Quarris** [comment]
Thats weird that this wasn't caught sooner. This should be already fixed from one of my previous changes, will push the version out 
to curseforge soon.
