### ISSUE TITLE
Grave has no localization

### ISSUE THREAD

**Issue by BlueAmulet** [Quarris/EnigmaticGraves#22]
When looking at the grave with a mod like Jade, the grave will simply appear as "entity.enigmaticgraves.grave"

Also the Grave Finder in JEI has "info.grave.remove_grave" listed as it's message.

**Comment by Quarris** [comment]
You must be playing on an older version of the mod

**Comment by BlueAmulet** [comment]
The latest version on curseforge,1.6.1, does not contain those entries.
![2021-09-05_105155](https://user-images.githubusercontent.com/43395286/132134889-12b79111-03f9-449f-a709-e3ae9246f9cf.png)

**Comment by Quarris** [comment]
Weird, I'll have a look

**Comment by Quarris** [comment]
Should be up for 1.6.2
