### ISSUE TITLE
Grave commands are accesible to all players

### ISSUE THREAD

**Issue by Darkere** [Quarris/EnigmaticGraves#23]
https://github.com/Quarris/EnigmaticGraves/blob/7c4d61e08bada3e26a0fd2c63d917d6c0b7bab1d/src/main/java/dev/quarris/enigmaticgraves/command/RestoreGraveCommand.java#L97

Redirects also need the `.requires(source -> source.hasPermissionLevel(2))`. Otherwise, they are accessible to all players.

**Comment by Quarris** [comment]
Are all of them accessible to everyone or just the help command?

**Comment by Darkere** [comment]
all of them

**Comment by Quarris** [comment]
Alllllright I'm doing a hotfix for this rn
