### ISSUE TITLE
Issue with item restoration upon claiming a grave

### ISSUE THREAD

**Issue by MuteTiefling** [Quarris/EnigmaticGraves#29]
Bit of a strange one. 

Mod Version: EnigmaticGraves-1.7.1.jar
Forge: 36.2.4

Video showing the process: https://streamable.com/8nh9bw

Steps to reproduce

1. Get Diamond Sword with Soulbound on it, plus one other enchant
2. Get another Diamond sword _without_ Soulbound on it, but with any other enchant
3. Go die 
4. Retrieve grave

You'll now have two of the Soulbound sword. The other sword is lost.
The player reporting this says they're unable to reproduce this without switching into Spectator between steps 3 and 4 above, but I did not switch game mode between deaths in the video. I did switch game modes in that play session, however, if this somehow makes a difference. 

https://github.com/NillerMedDild/Enigmatica6/issues/3694

**Comment by kaii-tech** [comment]
I have the same issue.

**Comment by IvyKirkland** [comment]
I found it with a couple of friends after they died fighting the Gaia guardian. Both of them had one soulbound sword.

**Comment by Quarris** [comment]
How have I not seen this issue from Nov? I just fixed it in Dev I believe. I'll try to fix some more issues and get a build out #soon #hopefully
