### ISSUE TITLE
Grave <ERROR>

### ISSUE THREAD

**Issue by VessQ** [Quarris/EnigmaticGraves#30]
Hello! Just recently started my Minecraft world and died to an ice and fire mob about a couple hours into exploring. When I traveled all 5,000 blocks back to get my grave, It would not let me pick up my stuff and hovering over the grave just displayed <error>. I was able to shift click and pick up the grave to move it, but not collect what was inside? I've tried to break it, left and right click... nothing works :( I can't get my stuff back.

**Comment by Quarris** [comment]
Are you able to send over the log file from when it happened? Try using the /grave restore command to get your stuff back
