### ISSUE TITLE
[1.16.5] Run back to grave Inventory wiped when restoring my grave.

### ISSUE THREAD

**Issue by ProsperCraft** [Quarris/EnigmaticGraves#31]
When I claimed my grave the items I had in my inventory to get to my grave were wiped and replaced with the items in the grave.  My inventory was not full in the grave or the run back to grave inventory.

Server Debug - https://gist.github.com/ProsperCraft/ea93927e91ab95018c6dad3b7999e9f6
Server latest - https://gist.github.com/ProsperCraft/6931af59cfe8d420aa12b526b9879b37

Client latest - https://gist.github.com/ProsperCraft/ad47d714e99eece058d768622d1c9836
Client debug - https://gist.github.com/ProsperCraft/1f32a85371dd71f92df9d22e482d4bab

EnigmaticGraves-1.7.1
forge-1.16.5-36.2.16

Modpack -[ TownCraft TWO for 1.16.5](https://www.curseforge.com/minecraft/modpacks/towncraft) -

**Comment by Quarris** [comment]
These logs aren't complete, let alone mentioning anyones death in them. I can't debug what the issue is from these :/
If the issue is still present in v1.7.3+ please reopen the issue and make sure the logs contain information about some death
