### ISSUE TITLE
Traveler's backpack is not going in the grave

### ISSUE THREAD

**Issue by jinkhya** [Quarris/EnigmaticGraves#32]
Hello,
After comparing with some other grave/tomb mods it looks like EnigmaticGraves is not letting the traveler's backpack in the grave but gets dropped on the floor. To test this you will have to turn backpackDeathPlace = true in traveler's backapack config. 
https://imgur.com/a/08zCwer

Forge 22 
TravelersBackpack 5.4.6
EnigmaticGraves 1.7.1

Thanks in advance ! 
Jin

**Comment by Quarris** [comment]
Can't seem to replicate the issue. Was the backpack in the Curio slot?

**Comment by Quarris** [comment]
Should be fixed in v1.7.2. Please have a look.

**Comment by jinkhya** [comment]
Awesome thank you ! It worked :)
