### ISSUE TITLE
Dropped items voided after being saved by lost trinkets ruby heart

### ISSUE THREAD

**Issue by theboo** [Quarris/EnigmaticGraves#33]
As seen in the gif below, if you "die" and are saved by lost trinkets ruby heart( a trinket that saves you from death if you had more than 3 hearts before you took enough damage to die), EG still prepares a grave in logs, but since you never actually die the grave is never actually placed. All items you drop in world get sent to the grave that never happens until you either die without the trinket or restart the world voiding anything dropped.

https://gyazo.com/087feb076aa01e5dbdb044272c597105

**Comment by Quarris** [comment]
[EnigmaticGraves-1.7.3.zip](https://github.com/Quarris/EnigmaticGraves/files/7961094/EnigmaticGraves-1.7.3.zip)
Can you try this and see if it helps?

**Comment by theboo** [comment]
Issue seems to still persist with this test jar
