### ISSUE TITLE
[Bug] Graves don't spawn and/or when they spawn they don't have items in them

### ISSUE THREAD

**Issue by Quarris** [Quarris/EnigmaticGraves#35]
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4494

**Comment by Quarris** [comment]
Okay, I've added a bunch more logging info for 1.7.4-logging version

It will be at https://www.curseforge.com/minecraft/mc-mods/enigmatic-graves/files/3723647 when it's approved, but its on Alpha so it won't show up directly on apps like Curseforge, so please have a direct look

**Comment by dajnoxes** [comment]
[debug.log](https://github.com/Quarris/EnigmaticGraves/files/8392394/debug.log)

**Comment by theboo** [comment]
^^ they aren't on the latest EG yet but I asked them to upload their debug log here just in case it has something useful

**Comment by Quarris** [comment]
Misclicked on the closing of the issue :P

**Comment by Quarris** [comment]
Okay, I fixed this particular issue. It might have fixed the other issue as well. I released a beta -- `1.7.4-hf1` -- which hopefully will be good

**Comment by dajnoxes** [comment]
> I does have something. @dajnoxes Do you know what the issue for for this case? Did the grave not spawn, or were the items gone?
> 
> Also, do you know if there was an item with Curse of Binding on the person that died (Dawiuu)?

Graves did not spawn. It occured after my 10 IQ friend dropped from a 150 blocks tall building, infected jungle temple dungeon. straight onto the ground on the vanilla frozen biome. Hope it will help somehow.

**Comment by dajnoxes** [comment]
When a player dies in a nether portal in nether dimension there is a chance their grave will spawn on coordinates from nether but in overworld. Just happned for our friend, he died in portal but his grave teleported into overworld with coords from nether
[latest.log](https://github.com/Quarris/EnigmaticGraves/files/8400073/latest.log)

**Comment by GeorgeWL** [comment]
I've had this happen a few times recently, the log isn't super helpful either tbh

```log
[16Apr2023 02:46:46.330] [Server thread/INFO] [dev.quarris.enigmaticgraves.EnigmaticGraves/]: Preparing grave for Cammo_353
[16Apr2023 02:46:46.332] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Cammo_353 was slain by Murmur
[16Apr2023 02:46:46.338] [Server thread/WARN] [dev.quarris.enigmaticgraves.EnigmaticGraves/]: Could not spawn grave for Cammo_353
[16Apr2023 02:46:46.338] [Server thread/INFO] [dev.quarris.enigmaticgraves.EnigmaticGraves/]: Added grave entry to player Cammo_353
```

**Comment by PvtFudgepants** [comment]
Just had this happen in my server. Log is very unhelpful and just says "Could not spawn grave". Any updates on this one?

**Comment by Quarris** [comment]
If the issue still persists, could someone send `debug.log` file with an updated mod version?
