### ISSUE TITLE
Enigmatic Graves item voidal

### ISSUE THREAD

**Issue by UnicorNora** [Quarris/EnigmaticGraves#36]
The player falls into a mob farm and got killed by a create deployer with a sword in it. You go back to your grave, but something is wrong, the grave when sneaking on it doesnt give you back your items and the deployer sucks them

**Comment by Quarris** [comment]
Which mod version are you using?

Can you define what you mean when you say the grave doesnt give items back AND the deployer sucks them? Do the items drop on the ground and the deployer does something to them? Whats going on there?
