### ISSUE TITLE
Graves delete first (left) item on action bar.

### ISSUE THREAD

**Issue by sabin13579** [Quarris/EnigmaticGraves#39]
Right clicking my grave will often, but not every time, delete any item in the first action bar slot. This includes items retrieved from the grave, typically my ethereal scythe from enigmatic legacy, but it will delete any item from what I can tell.

I'm running Monumental Experience pack, version 17.0.7 and EnigmagicGraves 1.16.5-1.7.4-hf2 in single player.
OP is on, not sure what other relevant details you need.

**Comment by JesseBS2** [comment]
Issue also occurs on EnigmaticGraves 1.18.1-1.7.4
 
 Good-bye to my enchanted sword :(

**Comment by Quarris** [comment]
I guess any server logs might come in handy if anyone has any

**Comment by sabin13579** [comment]
> Right clicking my grave 
It happens when I recover items from a grave. My stuff wasn't enchanted but only the first slot on the hotbar is affected.
It will delete an item recovered from a grave and/or items that were in the inventory prior to grave recovery.
Occurs with inventory space available.

I don't have logs from 6 months ago,

**Comment by Quarris** [comment]
Did it only happen with a non-stackable item, or do you recall with stackables too?

**Comment by sabin13579** [comment]
I don't think I tried with stackable items.
