### ISSUE TITLE
Graves don't store my Akashic Tome

### ISSUE THREAD

**Issue by vizthex123** [Quarris/EnigmaticGraves#41]
And it's rather annoying since I keep all my guidebooks there.

**Comment by Quarris** [comment]
Can't reproduce
https://gyazo.com/6168cf831425dc53637b4b2470cf89d0

You seem to be at least somewhat of a developer; You should know to provide more info that "it borked and its annoying"

**Comment by Quarris** [comment]
Please create a new issue about this and follow the provided template. Thank youu.
