### ISSUE TITLE
[Request] 1.19 version

### ISSUE THREAD

**Issue by vizthex123** [Quarris/EnigmaticGraves#42]
I would've just commented on the CF page, but it's been disabled there, so I'll make an issue report instead.

As the title says, I'd love to have this mod for Forge 1.19 since it's the best gravestone mod around.

**Comment by Timlyminer** [comment]
I would love that also

**Comment by Quarris** [comment]
Its up on Curseforge waiting for approval right now

**Comment by vizthex123** [comment]
noice, thanks
