### ISSUE TITLE
crash on load

### ISSUE THREAD

**Issue by VerserVarlin** [Quarris/EnigmaticGraves#43]
crashes on load

**To Reproduce**
1. Go to curceforge
2. download mod
3. run game

**Expected behavior**
the game to run without error

link to crash report
https://pastebin.com/5Z2aV3s3

**Versions (please complete the following information):**
 - Minecraft-Mod: 1.19-1.7.4
 - Forge: [e.g. 41.0.100]

**Comment by mimi-min** [comment]
I also have a crash on load issue.

Crash report: https://pastebin.com/Nhbfxp4a

Minecraft: 1.19
Mod ver.: 1.7.4
Forge: 41.0.1

**Comment by Quarris** [comment]
Im pretty sure this is fixed in v1.7.5
