### ISSUE TITLE
[SUGGESTION] Add option to config which allows any player to open graves 

### ISSUE THREAD

**Issue by EXFrost** [Quarris/EnigmaticGraves#44]
I suggest adding an option in the config which allows any player on a server to access any gravestone.
 This would be useful on PVP servers (otherwise killing a player has no reward) and Co-op playthroughs (where you may need to borrow your friends stuff to get your own grave). I've also seen other people want this feature on websites like Reddit also so I feel like this would be a good feature. 

And if this already is implemented in a non obvious way or there's a workaround in order to it already, could you tell me how to access it if so?

**Comment by zderApfel** [comment]
To add to this: Make it so you can destroy them PLEASE

**Comment by BlackAures1** [comment]
This feature is sorely lacking. Please add it.

**Comment by Quarris** [comment]
I've figured something out, however this required a little but of a rework. I'm going to release this as a beta build on CF for testing.
