### ISSUE TITLE
[BUG] When I removed the mod.

### ISSUE THREAD

**Issue by Valentin1234a** [Quarris/EnigmaticGraves#45]
I installed this mod on my server to try it out, but I had to delete it to replace it with a plugin.

After uninstalling it I don't know why but there is always a sign in the world that shows where I died and how many meters are missing until there. How do I remove this?

Ps. Yes I reset the server after deleting the mod.

**Comment by Valentin1234a** [comment]
![unknown](https://user-images.githubusercontent.com/113631323/190480972-6f0658c5-be1f-46ce-bbc5-348ee9391a33.png)

**Comment by Quarris** [comment]
This is not the fault of EG. You cannot code something like this by accident. You may have another mod that also tracks your waypoints, possibly even the plugin itself? I'm not sure, but this mod is not doing this.
