### ISSUE TITLE
[Feature Requests] A .json Model for the grave entity

### ISSUE THREAD

**Issue by Ks-Proj** [Quarris/EnigmaticGraves#47]
It would be nice to have the model of the grave in the assets folder as a .json model file to customize it with a resourcepack if even just the texture alone.

Also does the mod have a license? Can't find it anywhere on the mod page or Manifest files.

**Comment by Ks-Proj** [comment]
It would also be nice to have an option to disable sneak to retrieve items

**Comment by Quarris** [comment]
The model is hardcoded and I won't be turning it into a json file. The texture is already in the assets folder.

I can add config for sneaking
