### ISSUE TITLE
Grave restored Curious but not inventory.

### ISSUE THREAD

**Issue by Darkere** [Quarris/EnigmaticGraves#5]
I'm unable to reproduce this, but we've now had several reports of players picking up their grave and only receiving their Curios, but not the items that were in their inventory. Unsure how that could happen. 

EnigmaticGraves-1.1

**Comment by Quarris** [comment]
This is an old version. The newest version should have that fixed already

**Comment by Quarris** [comment]
^ Bad commit
Please open a new issue if this persist on the newest versions
