### ISSUE TITLE
[BUG] OP cannot loot player graves on server

### ISSUE THREAD

**Issue by ShamblerDK** [Quarris/EnigmaticGraves#53]
**Describe the bug**
I'm OP on our server but I can't loot player graves.

**Expected behavior**
OP players should be able to loot the graves.

**Versions (please complete the following information):**
 - Minecraft-Mod: 1.19.2-1.7.7
 - Forge: 43.2.21

**Comment by Quarris** [comment]
You can pick up an empty grave finder from creative menu and right click a grave with it to remove it (Note, this does not restore the items in the grave, use the `/enigmatic_graves <player> restore` command for that.
