### ISSUE TITLE
Issue With Sophisticated Backbacks

### ISSUE THREAD

**Issue by Areorah** [Quarris/EnigmaticGraves#56]
Step 1: Have a Sophisticated Backpack on (curios)
Step 2: Either placing certain items into the backpack (which I think is the addons, not completely sure) will cause it to bug when you die; may be caused due to have two backpacks, one wearing and one in your inventory)
Step 3: Claim grave; you will get all your items back, but the backpack that you had on won't come back. The grave still stays, which allows you infinitely dupe the items you had when you died.
![image](https://github.com/Quarris/EnigmaticGraves/assets/19559232/90b97b58-e9e0-4b6e-a753-57938a05b3f7)
![image](https://github.com/Quarris/EnigmaticGraves/assets/19559232/ca77fa82-ece4-4778-9e5d-19a610d5e6ea)
![image](https://github.com/Quarris/EnigmaticGraves/assets/19559232/225aa828-27e6-4a0f-819d-32fcc0679854)

Modpack: Enigmatica 9: Expert - E9E
Version: 1.13.0
Logs: https://mclo.gs/Ir8JQhW

**Comment by Quarris** [comment]
I have archived the latest mod version which should be causing this issue. Packs should be forced to downgrade if I'm not mistaken but it may have to be brought up with the pack devs so make sure it is downgraded
