### ISSUE TITLE
How to use backups?

### ISSUE THREAD

**Issue by F0gboy** [Quarris/EnigmaticGraves#6]
Ive gone to this stage:
/enigmatic_graves wuselom restore

and im not sure what to type after restore.

**Comment by Quarris** [comment]
You're right. I will fix that soon. For now all the entried begin with "death_" so if you start typing that it should find the entries.

**Comment by Quarris** [comment]
Fixed in [2bb7393](https://github.com/Quarris/EnigmaticGraves/commit/2bb739330c7783f3fa9169624282b34f402e4fd8)
