### ISSUE TITLE
Compat Request: Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by VallenFrostweaver** [Quarris/EnigmaticGraves#7]
I am requesting compatibility for this mod to restore Cosmetic Armor to the Cosmetic Armor slots as it does with Curios. If not going to be a thing then please feel free to close this out. :)

**Comment by Quarris** [comment]
This is a commission mod and I only add features that are requested and paid for. Unfortunately if I were to add compatibility for every mod I'd be here for my entire life :P 
I'll keep this open for future in case I find some time and motivation to work on this though, but it won't be any time soon.

**Comment by VallenFrostweaver** [comment]
Regardless, it's at least a reference pont in the future and may prevent the occasional other request.

**Comment by VallenFrostweaver** [comment]
@Quarris What is the best way to contact you for a commission possibility? I'll delete this post shortly so as not to be off topic.

**Comment by Quarris** [comment]
Discord, Im in Ellpecks. Quarris#8049
