### ISSUE TITLE
Using /enigmatic_graves NillerMedDild list while having 0 deaths causes error

### ISSUE THREAD

**Issue by NillerMedDild** [Quarris/EnigmaticGraves#8]
Using `/enigmatic_graves NillerMedDild list` while having 0 deaths causes error. Would be nice if it just said "You haven't died" or something similar

![billede](https://user-images.githubusercontent.com/21295394/125339287-73d30f00-e351-11eb-96cf-3608ca67b5a7.png)

**Comment by Quarris** [comment]
Fixed in v1.4.2
